/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorMantenimientoEstudiate;

/**
 *
 * @author Scarlett
 */
public class GuiBotones extends javax.swing.JPanel {

    /**
     * Creates new form GuiBotones
     */
    public GuiBotones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonBuscar = new javax.swing.JButton();
        botoAgregar = new javax.swing.JButton();
        botonEdditar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonGuardarDatos = new javax.swing.JButton();

        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botoAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        botoAgregar.setText("Agregar");

        botonEdditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar.png"))); // NOI18N
        botonEdditar.setText("Editar");

        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonGuardarDatos.setText("Guardar Datos");
        botonGuardarDatos.setEnabled(false);
        botonGuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(botoAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEdditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonGuardarDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botoAgregar)
                    .addComponent(botonBuscar)
                    .addComponent(botonEdditar)
                    .addComponent(botonGuardarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminar))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonGuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarDatosActionPerformed
     public void agregarEvento(ControladorMantenimientoEstudiate me){
         this.botoAgregar.addActionListener(me);
         this.botonBuscar.addActionListener(me);
         this.botonEdditar.addActionListener(me);
         this.botonEliminar.addActionListener(me);
         this.botonGuardarDatos.addActionListener(me);
         
     }
     
     public void setBoton(boolean re){
         this.botonGuardarDatos.setEnabled(re);
     }
     
     public int getCodigoPorFuente(Object object){
         int dev=0;
         
         if(this.botoAgregar.equals(object)){
             dev=ControladorMantenimientoEstudiate.AGREGAR;
         }else if(this.botonBuscar.equals(object)){
             dev=ControladorMantenimientoEstudiate.BUSCAR;
            
         }else if (this.botonEdditar.equals(object)) {
             dev=ControladorMantenimientoEstudiate.EDITAR;
             
        }else if(this.botonEliminar.equals(object)){
            dev=ControladorMantenimientoEstudiate.ELIMINAR;
            
        }else if (this.botonGuardarDatos.equals(object)) {
             dev=ControladorMantenimientoEstudiate.GUARDAR;
         }
         return dev;
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoAgregar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEdditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardarDatos;
    // End of variables declaration//GEN-END:variables

    
    
}
