/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControlGuiProf;
import Modelo.RegistroProfesor;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Scarlett
 */
public class GUIProfesor extends javax.swing.JFrame {

    /**
     * Creates new form GUIProfesor
     */
    private ControlGuiProf controlGuiProf;
    public GUIProfesor(RegistroProfesor rp) {
        initComponents();
        this.controlGuiProf=new ControlGuiProf(this,rp);
        this.botonesManejoProfesor1.agregarEvento(controlGuiProf);
    }

    public int getCodigoPorFuente(Object object){
        int dev=0;
        dev=this.botonesManejoProfesor1.getCodigoPorFuente(object);
        return dev;
    }

    public int getjTxtCedula() {
        return Integer.parseInt(this.jTxtCedula.getText());
    }

    public void setjTxtCedula(int jTxtCedula) {
        this.jTxtCedula.setText(String.valueOf(jTxtCedula));
    }

    public String getjTxtCorreo() {
        return this.jTxtCorreo.getText();
    }

    public void setjTxtCorreo(String jTxtCorreo) {
        this.jTxtCorreo.setText(jTxtCorreo);
    }

    public int getjTxtHorario() {
        return Integer.parseInt(this.jTxtHorario.getText());
    }

    public void setjTxtHorario(int jTxtHorario) {
        this.jTxtHorario.setText(String.valueOf(jTxtHorario));
    }

    public String getjTxtNombre() {
        return jTxtNombre.getText();
    }

    public void setjTxtNombre(String jTxtNombre) {
        this.jTxtNombre.setText(jTxtNombre);
    }
    
    public boolean verificarCampoCedula(){
        boolean dev=false;
        if(this.jTxtCedula.getText().equals("")){
            dev=true;
        }
        return dev;
    }
    
    public boolean verificar(){
        boolean dev=false;
            if(this.jTxtNombre.getText().equals("")||this.jTxtCedula.getText().equals("")||this.jTxtCorreo.getText().equals("")||this.jTxtHorario.equals("")){
                dev=true;
            }
        return dev;
    }

    public void setBotonModi(boolean res){
        this.botonesManejoProfesor1.getbModificar().setEnabled(res);
    }
    public void setEditaCedu(boolean res){
        this.jTxtCedula.setEditable(res);
    }
   
    public void limpiar(){
        this.jTxtCedula.setText("");
        this.jTxtCorreo.setText("");
        this.jTxtHorario.setText("");
        this.jTxtNombre.setText("");
    }
    public void setLabelMessage(String labelMessage) {
        this.labelMessage.setText(labelMessage);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtNombre = new javax.swing.JTextField();
        jTxtCedula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtCorreo = new javax.swing.JTextField();
        jTxtHorario = new javax.swing.JTextField();
        botonesManejoProfesor1 = new Vista.BotonesManejoProfesor();
        labelMessage = new javax.swing.JLabel();

        jLabel1.setText("Nombre");

        jLabel2.setText("Cedula");

        jLabel3.setText("Correo");

        jLabel4.setText("Horario");

        jTxtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCorreoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTxtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                .addComponent(jTxtCedula)
                                .addComponent(jTxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(botonesManejoProfesor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jTxtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(labelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botonesManejoProfesor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCorreoActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.BotonesManejoProfesor botonesManejoProfesor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTxtCedula;
    private javax.swing.JTextField jTxtCorreo;
    private javax.swing.JTextField jTxtHorario;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JLabel labelMessage;
    // End of variables declaration//GEN-END:variables
}
