/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControlMantenimientoCursos;
import Controlador.ControladorMantenimientoEstudiate;

/**
 *
 * @author Scarlett
 */
public class PanelBotonesCursos extends javax.swing.JPanel {

    /**
     * Creates new form PanelBotonesCursos
     */
    public PanelBotonesCursos() {
        initComponents();
    }

    public void agregarEvento(ControlMantenimientoCursos controlMantenimientoCursos){
        this.jBotonAgregar.addActionListener(controlMantenimientoCursos);
        this.jBotonConsultar.addActionListener(controlMantenimientoCursos);
        this.jBotonEliminar.addActionListener(controlMantenimientoCursos);
        this.jBotonModificar.addActionListener(controlMantenimientoCursos);
        this.JBotonGuardar.addActionListener(controlMantenimientoCursos);
    }
    
    public void setBoton(boolean re){
         this.JBotonGuardar.setEnabled(re);
     }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBotonAgregar = new javax.swing.JButton();
        jBotonConsultar = new javax.swing.JButton();
        jBotonModificar = new javax.swing.JButton();
        jBotonEliminar = new javax.swing.JButton();
        JBotonGuardar = new javax.swing.JButton();

        jBotonAgregar.setText("Agregar");
        jBotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonAgregarActionPerformed(evt);
            }
        });

        jBotonConsultar.setText("Consultar Curso");

        jBotonModificar.setText("Modificar");

        jBotonEliminar.setText("Eliminar");

        JBotonGuardar.setText("Guardar");
        JBotonGuardar.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBotonAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBotonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBotonGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBotonEliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jBotonConsultar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonAgregar)
                    .addComponent(jBotonModificar)
                    .addComponent(jBotonEliminar)
                    .addComponent(JBotonGuardar))
                .addGap(18, 18, 18)
                .addComponent(jBotonConsultar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBotonAgregarActionPerformed

    public int getCodigoPorfuente(Object object) {
        int dev = 0;
        if (this.jBotonAgregar.equals(object)) {
            dev = ControlMantenimientoCursos.AGREGAR;
        }
        if (this.jBotonConsultar.equals(object)) {
            dev = ControlMantenimientoCursos.CONSULTAR;
        }
        if (this.jBotonEliminar.equals(object)) {
            dev = ControlMantenimientoCursos.ELIMINAR;
        }
        if (this.jBotonModificar.equals(object)) {
            dev = ControlMantenimientoCursos.MODIFICAR;

        }if(this.JBotonGuardar.equals(object)){
            dev=ControlMantenimientoCursos.GUARDAR;
        }
        return dev;

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBotonGuardar;
    private javax.swing.JButton jBotonAgregar;
    private javax.swing.JButton jBotonConsultar;
    private javax.swing.JButton jBotonEliminar;
    private javax.swing.JButton jBotonModificar;
    // End of variables declaration//GEN-END:variables
}
